name: Auto Scrape Hot News GenZ

on:
  schedule:
    # Chạy vào phút 0 của các giờ 0, 6, 12, 18 (6 tiếng/lần)
    - cron: '0 */6 * * *' 
  workflow_dispatch: # Cho phép bấm chạy thủ công

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pipeline
      env:
        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GHT_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: python main.py
